jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enablePublishBuildArtifacts: true
      jobs:
        - job: Validate_Helix
          displayName: Validate Helix
          variables:
          - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
            - group: DotNet-HelixApi-Access
          - _BuildConfig: Release
          steps:
          - template: /eng/common/templates/steps/send-to-helix.yml
            parameters:
              HelixType: test/product/
              XUnitProjects: $(Build.SourcesDirectory)/src/Validation/tests/Validation.Tests.csproj
              XUnitTargetFramework: netcoreapp2.0
              XUnitRunnerVersion: 2.4.1
              IncludeDotNetCli: true
              DotNetCliPackageType: sdk
              DotNetCliVersion: 2.1.403
              EnableXUnitReporter: true
              WaitForWorkItemCompletion: true
              ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
                HelixTargetQueues: Windows.10.Amd64.Open;Ubuntu.1604.Amd64.Open
                HelixSource: pr/dotnet/arcade-validation/$(Build.SourceBranch)
                IsExternal: true
                creator: arcade-validation
              ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
                HelixTargetQueues: Windows.10.Amd64;Ubuntu.1604.Amd64
                HelixSource: official/dotnet/arcade-validation/$(Build.SourceBranch)
                HelixAccessToken: $(HelixApiAccessToken)