jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enablePublishBuildArtifacts: true
      jobs:
        - job: Validate_Helix
          displayName: Validate Helix
          variables:
            - group: DotNet-HelixApi-Access
            - _BuildConfig: Release
          steps:      
          - template: /eng/common/templates/steps/send-to-helix.yml
            parameters:
              HelixSource: pr/dotnet/arcade-validation/$(Build.SourceBranch)
              HelixType: test/product/
              HelixTargetQueues: Windows.81.Amd64.Open;Ubuntu.1604.Amd64.Open
              XUnitProjects: $(Build.SourcesDirectory)/src/Validation/tests/Validation.Tests.csproj
              XUnitTargetFramework: netcoreapp2.0
              XUnitRunnerVersion: 2.4.1
              IncludeDotNetCli: true
              DotNetCliPackageType: sdk
              DotNetCliVersion: 2.1.403
              EnableXUnitReporter: true
              WaitForWorkItemCompletion: true
              IsExternal: true
              Creator: arcade-validation
              HelixAccessToken: $(HelixApiAccessToken)