variables:
  - name: Build.Repository.Clean
    value: true
  - name: _HelixType
    value: build/product
  - name: _HelixSource
    value: pr/dotnet/arcade-minimalci-sample/$(Build.SourceBranch)
  - name: _HelixTestType
    value: test/product/
  - name: _XUnitProject
    value: $(Build.SourcesDirectory)/src/Validation/tests/Validation.Tests.csproj
  - name: _XUnitTargetFramework
    value: netcoreapp2.0
  - name: _XUnitRunnerVersion
    value: 2.4.1
  - name: _DotNetCliPackageType
    value: sdk
  - name: _DotNetCliVersion
    value: 2.1.403
  - name: _Creator
    value: arcade-validation
  - name: _ArtifactsBaseFolder
    value: Helix
  - group: Helix Anonymous
jobs:
  - template: /eng/common/templates/steps/send-to-helix.yml
      parameters:
        HelixSource: $(_HelixSource)
        HelixType: $(_HelixTestType)
        HelixTargetQueues: Windows.10.Amd64.Open;Windows.81.Amd64.Open;Windows.7.Amd64.Open
        HelixAccessToken: $(BotAccount-dotnet-github-anon-kaonashi-bot-helix-token)
        XUnitProjects: $(_XUnitProject)
        XUnitTargetFramework: $(_XUnitTargetFramework)
        XUnitRunnerVersion: $(_XUnitRunnerVersion)
        IncludeDotNetCli: true
        DotNetCliPackageType: $(_DotNetCliPackageType)
        DotNetCliVersion: $(_DotNetCliVersion)
        EnableXUnitReporter: true
        WaitForWorkItemCompletion: true
        IsExternal: true
        Creator: $(_Creator)
  - template: /eng/common/templates/steps/send-to-helix.yml
      parameters:
        HelixSource: $(_HelixSource)
        HelixType: $(_HelixTestType)
        HelixTargetQueues: Debian.9.Amd64.Open;Fedora.27.Amd64.Open;RedHat.7.Amd64.Open;Ubuntu.1604.Amd64.Open
        HelixAccessToken: $(BotAccount-dotnet-github-anon-kaonashi-bot-helix-token)
        XUnitProjects: $(_XUnitProject)
        XUnitTargetFramework: $(_XUnitTargetFramework)
        XUnitRunnerVersion: $(_XUnitRunnerVersion)
        IncludeDotNetCli: true
        DotNetCliPackageType: $(_DotNetCliPackageType)
        DotNetCliVersion: $(_DotNetCliVersion)
        EnableXUnitReporter: true
        WaitForWorkItemCompletion: true
        IsExternal: true
        Creator: $(_Creator)